title: 功能大厅
hidden: true
content:
  - tag: grid
    header: false
    content:
      - text: 校园地图
        color: orange
        name: Map
        icon: /icon/tabPage/map.svg
        url: map
      - text: 音律东师
        color: red
        name: Music
        icon: /icon/tabPage/music.svg
        url: player
      - text: 体测计算器
        color: blue
        name: PE Calculator
        icon: /icon/tabPage/calculate.svg
        url: PEcal
      - text: 校历
        color: purple
        name: Calendar
        icon: /icon/tabPage/calendar.svg
        url: calendar
