- tag: list
  head: 更新日志
  content:
    - text: |-
        V 2.4.2：
        修复 NENU　主题的显示问题。
         · 新增校历
         · 改进 phone 与 doc 组件
    - text: |-
        V 2.3.0：
        重构我的东师tab页，联系客服、bug反馈更清晰。
         · 新增存储设置
         · 新增授权设置
    - text: |-
        V 2.2.2：
        增加搜索功能，精彩指南内容，一搜即达。
         · 主页与东师攻略页面上方增加搜索栏，支持东师攻略页面的关键词搜索
    - text: |-
        V 2.1.7：
        添加天气页面
         · 天气页面UI完全重做，支持更多天气详情。
    - text: 查看详细日志
      aim: log0
