title: 功能大厅
grey: true
hidden: true
content:
  - tag: card
    type: page
    src: http://v3.mp.innenu.com/img/tab/map.jpg
    title: 校园地图
    logo: /icon/tabPage/map.svg
    url: map

  - tag: card
    type: page
    src: http://v3.mp.innenu.com/img/tab/headphone.jpg
    title: 音律东师
    logo: /icon/tabPage/music.svg
    url: player

  - tag: card
    type: page
    src: http://v3.mp.innenu.com/img/tab/calendar.jpg
    title: 校历
    logo: /icon/tabPage/calendar.svg
    url: calendar

  - tag: card
    type: page
    src: http://v3.mp.innenu.com/img/tab/sport-field.jpg
    title: 体测计算器
    logo: /icon/tabPage/calculate.svg
    url: PEcal
