title: 东师指南
grey: true
hidden: true
content:
  - tag: grid
    header: 学在东师
    content:
      - text: 课程
        color: blue
        name: Course
        icon: /icon/tabPage/course.svg
        path: /course/
      - text: 学习
        color: orange
        name: Study
        icon: /icon/tabPage/study.svg
        path: /study/
      - text: 图书馆
        color: red
        name: Library
        icon: /icon/tabPage/library.svg
        path: /library/
      - text: 考试
        color: purple
        name: Exam
        icon: /icon/tabPage/test.svg
        path: /test/
  - tag: grid
    header: 行在东师
    content:
      - text: 校园卡
        color: blue
        name: Card
        icon: /icon/tabPage/card.svg
        path: /card/
      - text: 账户
        color: orange
        name: Account
        icon: /icon/tabPage/account.svg
        path: /account/
      - text: 食堂
        color: red
        name: Dining
        icon: /icon/tabPage/dining.svg
        path: /dining/
      - text: 生活
        color: purple
        name: Life
        icon: /icon/tabPage/life.svg
        path: /life/
      - text: 寝室
        color: cyan
        name: Dorm
        icon: /icon/tabPage/dorm.svg
        path: /dorm/
      - text: 校园网
        color: olive
        name: Network
        icon: /icon/tabPage/network.svg
        path: /network/
      - text: 资助
        color: mauve
        name: Subsidize
        icon: /icon/tabPage/subsidize.svg
        path: /subsidize/
  - tag: grid
    header: 乐在东师
    content:
      - text: 学生组织
        color: blue
        name: Orgnazation
        icon: /icon/tabPage/studentOrg.svg
        path: /studentOrg/
      - text: 社团
        color: orange
        name: Coporation
        icon: /icon/tabPage/corporation.svg
        path: /corporation/
      - text: 交通
        color: red
        name: Traffic
        icon: /icon/tabPage/traffic.svg
        path: /traffic/
      - text: 吃喝玩乐
        color: purple
        name: Nearby
        icon: /icon/tabPage/nearby.svg
        path: /nearby/
  - tag: grid
    header: 关于东师
    content:
      - text: 学校概况
        color: blue
        name: Description
        icon: /icon/tabPage/about.svg
        path: /about/
      - text: 学校机构
        color: orange
        name: Apartment
        icon: /icon/tabPage/apartment.svg
        path: /apartment/
  - tag: grid
    header: 新生你好
    content:
      - text: SIM卡
        color: blue
        name: SIM
        icon: /icon/tabPage/sim.svg
        path: /sim/
      - text: 新生报到
        color: orange
        name: Check
        icon: /icon/tabPage/check.svg
        path: /check/
