title: 首页
grey: true
hidden: true
content:
  - tag: title
    text: 新生们最关心的问题

  - tag: list
    header: 寝室
    content:
      - text: 本部校区
        path: benbu

      - text: 净月校区
        path: jingyue

      - text: 室内布局
        path: detail

      - text: 公共区域
        path: public

  - tag: list
    header: 食堂
    content:
      - text: 本部校区有北苑餐厅和南苑餐厅两个食堂。

      - text: 北苑餐厅
        path: beiyuan/

      - text: 南苑餐厅
        path: nanyuan/

      - text: 净月校区有两个食堂，分别为一食堂和二食堂。

      - text: 一食堂
        path: dining-1

      - text: 二食堂
        path: dining-2

  - tag: list
    header: 课程
    content:
      - text: 本科课程计划
        icon: plan
        path: plan

      - text: 获取双学位与辅修
        icon: /icon/tabPage/course.svg
        path: double-degree

      - text: 转专业实施办法及注意事项
        icon: /icon/tabPage/course.svg
        path: change-major

  - tag: text
    heading: " "
    type: p
    text: "如果您还有什么疑问，但是小程序中没有提及的，欢迎联系 QQ 1178522294 咨询。"
    style:
      color: "#888"
      font-size: 14px
