title: 申请流程
shareable: true
contact: true
content:
  - tag: title
    text: 资助申请流程
  - tag: text
    heading: false
    text: 入学后，学校统一组织资助对象认定，对于获得资助对象资格的家庭经济困难学生给予相应资助。
  - tag: title
    text: 资助对象申请流程
  - tag: img
    src: "https://v3.mp.innenu.com/img/subsidize/subsidize1.png"
  - tag: title
    text: 勤工助学岗位申请流程
  - tag: img
    src: "https://v3.mp.innenu.com/img/subsidize/subsidize2.png"
  - tag: footer
    author: Mr.Hope
    time: 2019年6月27日
