name: Deploy resource to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan mp.innenu.com >> ~/.ssh/known_hosts
          git config --global user.name 'Mr.Hope'
          git config --global user.email 'zhangbowang1998@gmail.com'
          git log
          ls
      - name: Deploy
        run: git push -f git@mp.innenu.com:/www/wwwroot/mp master
